### PR TITLE
Overhaul companion section and move sdcard contents

### PR DESCRIPTION
**Pull request by schwabe**

### CODE REVIEW

**Comment by RCdiy** [comment]
We need a way of easily cross linking. When/if I work on the SD Card content
- I would suggest a new page
- It could have SD Card related details
- It will have a general over view not details of each directory.
- It will say something like SOUNDS see (and a link to the Audio page)
- Crossfire see (and a link to the crossfire page
- Images see ( and a link to the Images page)
- Similarly each destination page will have a link back, SD Card Contents see (and a link to SD card page)

There are three ways I look for information
- I want Audio/Wizards/calibrate S6R, what do I do?
- What is the SD card for? Where do I get the files?
- Read a manual A-Z, but that is becoming rare:)

**Comment by schwabe** [comment]
We might extra an sdcard.md that only gives an overview of the sdcard and links to the specialised sections. Lets just improve incremental and not try to have the perfect thing in the first place.

**Comment by RCdiy** [comment]
I would put the the text back in Audio.... It is specific to audio but a subset of SD card contents.... I specifically put it in audio so readers don't have to jump about... Also it would help if you came up with a master plan of how you want documentation handled... we need someone to take the lead and coordinate all our efforts... a workflow similar to the code workflow so we have some idea of what to expect....

**Comment by RCdiy** [comment]
Lets create a Top Level file so SD Card Contents. See #28

**Comment by schwabe** [comment]
I moved sdcard to its own category and link from to/it. This that more in line what you expect?

**Comment by schwabe** [comment]
@RCdiy since you review this already can you check if you are still okay with that? I.e. if it is an improvement over what it is there. If you have another better idea how to structure it we can just do another pull request/commit.

**Review by powercycle — COMMENTED** [review]
This looks pretty good.  Why did you remove the contributors page?   I would agree it needs improvements, but it makes sense that we give credit where it is due.

@RCdiy, is this ready to be added as is, or do you have more changes you would like to make before committing?

Any other suggestions by anyone else?

**Comment by schwabe** [comment]
@powercycle contributers page is outdated. I did not remove it but replace it with a link to the contributions page for the main project. To better reflect who worked on the manual we can add a manual section there.

**Comment by powercycle** [comment]
Thanks.  I saw that after I posted the comment.  Thanks.

**Pull request merged**
