### PR TITLE
Added s.port flashing documentation

### PR DESCRIPTION
**Pull request by RCdiy**

### CODE REVIEW

**Review by 3djc — COMMENTED** [review]
I can still see some bmp which I believe are non needed since png are available

**Comment by RCdiy** [comment]
BMPs removed :)

**Comment by schwabe** [comment]
I think you forgot to commit and/or push that change

**Comment by RCdiy** [comment]
I think I have it fixed now...

**Comment by 3djc** [comment]
Thanks 👍

**Pull request merged**
